include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AxsRebornPrefs

AxsRebornPrefs_FILES = Controllers/AxsRootListController.m
AxsRebornPrefs_FRAMEWORKS = UIKit Foundation
AxsRebornPrefs_PRIVATE_FRAMEWORKS = Preferences
AxsRebornPrefs_INSTALL_PATH = /Library/PreferenceBundles
AxsRebornPrefs_CFLAGS = -fobjc-arc -IControllers

include $(THEOS_MAKE_PATH)/bundle.mk
